FROM susannasalata/pocket_memory:latest

# set environmetn variables
ENV JWT_SECRET_KEY=qwerty
ENV JWT_REFRESH_SECRET_KEY=ytrew
ENV MONGO_CONNECTION_STRING=mongodb+srv://VadymKu:k*V190821@cluster0.nrqiq.mongodb.net/?retryWrites=true&w=majority


# Run the image as a non-root user
RUN adduser -D myuser
USER myuser

# $PORT is set by Heroku
# CMD gunicorn --bind 0.0.0.0:$PORT wsgi
CMD uvicorn app:app --host 0.0.0.0:$PORT