FROM susannasalata/pocket_memory:latest

# Run the image as a non-root user
RUN adduser -D myuser
USER myuser

# $PORT is set by Heroku
# CMD gunicorn --bind 0.0.0.0:$PORT wsgi
CMD uvicorn app:app --host 0.0.0.0 --port $PORT